name: Crowdin - Upload strings
on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.repository == 'Drapersniper/Audio'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        curl https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
        echo "deb https://artifacts.crowdin.com/repo/deb/ /" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update -qq
        sudo apt-get install -y crowdin
        pip install redgettext==3.4.2
    - name: Generate source files
      run: |
        python3.8 -m redgettext --command-docstrings --verbose --recursive audio
    - name: Upload source files
      run: |
        crowdin upload sources
      env:
        CROWDIN_API_KEY: ${{ secrets.crowdin_token}}
        CROWDIN_PROJECT_ID: ${{ secrets.crowdin_identifier }}
