name: Pre-commit
on:
    pull_request:
    push:

permissions:
    issues: write

jobs:
    pre-commit-fixes:
        name: Pre-commit fixes
        runs-on: [self-hosted, linux, x64]
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-python@v4
            with:
                python-version: '3.11'
        -   uses: pre-commit/action@v3.0.0
        -   uses: pre-commit-ci/lite-action@v1.0.1
            if: always()
